<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\web\AssetBundle;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class MAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    // public $css = [
    //     "css/web/bootstrap.min.css",
    //     "font-awesome/css/font-awesome.css",
    //     "css/web/style.css?ver=".RELEASE_VERSION
    // ];
    // public $js = [
    //     "plugins/jquery-2.1.1.js",
    //     "js/web/bootstrap.min.js",
    //     "js/web/common.js?ver=".RELEASE_VERSION
    // ];
    public function registerAssetFiles($view)
    {
    	//因为版本号是一个常量，需要计算才能写入
    	//加载JS或者CSS是有业务逻辑的，根据条件加载CSS，需要逻辑计算
    	$release_version = defined('RELEASE_VERSION')?RELEASE_VERSION:time();
    	$this->css = [
        "/font-awesome/css/font-awesome.css",
        "/css/m/css_style.css",
        "/css/m/app.css?ver=".$release_version
    	];

    	$this->js = [
		"http://res.wx.qq.com/open/js/jweixin-1.2.0.js",
        "plugins/jquery-2.1.1.js",
        "js/m/TouchSlide.1.1.js",
        "js/m/common.js?ver=".$release_version,
		"js/m/weixin.js?ver=".$release_version,
    	];
    	parent::registerAssetFiles($view); //TODO:Change the autogenerated stub 
    }



} 